import { Open_Sans } from "next/font/google";
import "./globals.css";
import "./styles.css";
import "modern-normalize";
import Head from "next/head";
import NavBar from "@/components/NavBar/NavBar";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import StoreProvider from "./StoreProvider";

const openSans = Open_Sans({
  weight: ["300"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Test Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={openSans.className}>
        <StoreProvider>
          <ToastContainer
            position="top-center"
            autoClose={1500}
            theme="light"
          />

          <header className="header">
            <NavBar />
          </header>

          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
